name: Deploy to OpenShift

on:
  push:
    branches: [ main ]  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: self-hosted  # uses your self-hosted runner in OCP

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to OpenShift
        run: |
          oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
          oc project "$OPENSHIFT_NAMESPACE"

      - name: Deploy to OpenShift
        run: |
          # Example: Apply all Kubernetes resources in the 'openshift' folder
          oc apply -f openshift/

          # Or, if you want to restart a specific deployment
          # oc rollout restart deployment/<your-app-name>
